// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _210GroupProject.Models;

namespace _210GroupProject.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20190411215654_listidint2")]
    partial class listidint2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("_210GroupProject.Models.ListOfPlaces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserId");

                    b.Property<bool>("isPublished");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DbOfLists");
                });

            modelBuilder.Entity("_210GroupProject.Models.Place", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ImageURL");

                    b.Property<int>("ListId");

                    b.Property<int?>("ListOfPlacesId");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("PriceRange");

                    b.Property<int>("Rating");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("ListOfPlacesId");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("_210GroupProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DbOfUsers");
                });

            modelBuilder.Entity("_210GroupProject.Models.ListOfPlaces", b =>
                {
                    b.HasOne("_210GroupProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("_210GroupProject.Models.Place", b =>
                {
                    b.HasOne("_210GroupProject.Models.ListOfPlaces")
                        .WithMany("LOfPlaces")
                        .HasForeignKey("ListOfPlacesId");
                });
#pragma warning restore 612, 618
        }
    }
}
