// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _210GroupProject.Models;

namespace _210GroupProject.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("_210GroupProject.Models.ListOfPlaces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsPublished");

                    b.Property<string>("ListTitle")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("_210GroupProject.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("ImageURL")
                        .IsRequired();

                    b.Property<int>("ListId");

                    b.Property<int?>("ListOfPlacesId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("PriceRange");

                    b.Property<int>("Rating");

                    b.Property<string>("URL")
                        .IsRequired();

                    b.Property<string>("YelpId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ListOfPlacesId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("_210GroupProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_210GroupProject.Models.ListOfPlaces", b =>
                {
                    b.HasOne("_210GroupProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_210GroupProject.Models.Place", b =>
                {
                    b.HasOne("_210GroupProject.Models.ListOfPlaces")
                        .WithMany("Places")
                        .HasForeignKey("ListOfPlacesId");
                });
#pragma warning restore 612, 618
        }
    }
}
